adiutor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import homepage

from accounts.urls import urlpatterns as accounts_urls


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('verification/', include('verify_email.urls')),
    path('', homepage, name='homepage'),
    path('main/', include('main.urls')),
    path('accounts/', include((accounts_urls, 'accounts'), namespace='accounts')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.contrib.auth.decorators import permission_required
from .views import (cadastrar_paciente, add_entrada, index, list_entradas,
                    cadastro_user_terapeuta, informacoes_terapeuta,
                    desligar_paciente, transferir_paciente, admin_interface, detalhes_grupo,
                    novo_convenio, detalhes_paciente, cadastrar_grupo, transferir_grupo, index_perfil,
                    add_entrada_sessao_grupo, add_pacientes_to_grupo, list_entradas_grupo, desligar_grupo,
                    modificar_cadastro_profissionais, producao_mensal, handle_error, cadastro_historico_academico,
                    terapeuta_media_upload, paciente_media_upload, redirect_to_homepage, view_certificado_curso,
                    view_paciente_pdf, view_paciente_images, view_terapeuta_images, view_terapeutas_pdf,
                    remover_membro_grupo, religar_paciente)

app_name = 'main'

urlpatterns = [
    path('novo/',
         cadastrar_paciente,
         name='novo'),
    path('add_pac_grupo/<str:grupo_id>/',
         add_pacientes_to_grupo,
         name='add-pacs-grupo'),

    path('add_entrada/<str:prontuario_numero>/',
         permission_required('main.add_entry')(add_entrada),
         name='add_entrada'),

    path('desligamento/<str:prontuario_numero>/',
         permission_required('main.deslig_pac')(desligar_paciente),
         name='desligamento'),

    path('reativar/<str:prontuario_numero>/',
         religar_paciente, name='religamento'),

    path('transfer/<str:prontuario_numero>/',
         permission_required('main.transfer_pac')(transferir_paciente),
         name='transferencia'),

    path('prontuario/<str:prontuario_numero>/',
         list_entradas,
         name='prontuario'),

    path('index/',
         index,
         name='index'),

    path('indice_cadastros',
         index_perfil,
         name='index-perfil'),

    path('usuario/',
         permission_required('main.add_terapeuta')(cadastro_user_terapeuta),
         name='usuario'),

    path('administrativo/',
         admin_interface,
         name='administrativo'),

    path('convenio/',
         permission_required('main.add_convenio')(novo_convenio),
         name='convenio'),

    path('perfil/<str:terapeuta_codigo>',
         informacoes_terapeuta,
         name='perfil'),

    path('dadospac/<str:prontuario_numero>/',
         detalhes_paciente,
         name='dadospac'),

    path('add-entrada-grupo/<str:prontuario_grupo_numero>/',
         permission_required('main.add_entry_group')(add_entrada_sessao_grupo),
         name='add-entrada-grupo'),

    path('add_grupo/',
         permission_required('main.create_group')(cadastrar_grupo),
         name='add-grupo'),

    path('add_pac_grp/<str:grupo_id>',
         add_pacientes_to_grupo, name='add-pac-grupo'),
    # path('add_pac_grp', add_pacientes_to_grupo, name='add-pac-grupo'),

    path('grupo_prontuario/<str:prontuario_grupo_numero>/',
         list_entradas_grupo,
         name='grupo-prontuario'),

    path('transfer_grupo/<str:prontuario_grupo_numero>/',
         permission_required('main.transfer_group')
         (transferir_grupo),
         name='transfer-grupo'),

    path('deslig_grupo/<str:prontuario_grupo_numero>',
         permission_required('main.deslig_group')(desligar_grupo),
         name='deslig-grupo'),

    path('dados_grupo/<str:prontuario_grupo_numero>/',
         detalhes_grupo,
         name='dados-grupo'),

    path('error',
         handle_error,
         name='handle-error'),

    path('cadastrar_formacao/<str:terapeuta_codigo>/',
         cadastro_historico_academico,
         name='cadastrar_formacao'),

    path('modificar/terapeuta/<str:terapeuta_codigo>/',
         # permission_required(CREATE-PERMISSION)(),
         modificar_cadastro_profissionais,
         name='modificar-terapeuta'),

    path('producao/gerar/',
         producao_mensal,
         name='gerar-producao'),

    # path('producao/render/',
    #      render_producao,
    #      name='render-producao'),

    path('enviar_arquivo_terapeuta/<str:terapeuta_codigo>/',
         terapeuta_media_upload,
         name='enviar_arquivo_terapeuta'),

    path('enviar_arquivo_paciente/<str:prontuario_numero>',
         paciente_media_upload,
         name='enviar_arquivo_paciente'),

    path('homepage',
         redirect_to_homepage,
         name='homepage'),

    path('view_certificado/<int:curso_id>/',
         view_certificado_curso,
         name='view_certificado'),

    path('view_paciente_files/pdf/<int:media_id>',
         view_paciente_pdf,
         name='paciente/pdf'),

    path('view_paciente_images/image/<int:media_id>',
         view_paciente_images,
         name='paciente/image'),

    path('view_terapeuta_files/image/<int:media_id>',
         view_terapeuta_images,
         name='terapeuta/image'),

    path('view_terapeuta_files/pdf/<int:media_id>',
         view_terapeutas_pdf,
         name='terapeuta/pdf'),

    path('remove_grupo_member/<str:prontuario_numero>/<str:prontuario_grupo_numero>',
         permission_required('main.remove_pac_from_group')(remover_membro_grupo),
         name='remove_paciente')
]

main/models.py
import os
import re
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MinValueValidator, MaxValueValidator
from accounts.models import CustomUser
from datetime import date, datetime


def create_prontuario_numero():
    """ Cria um novo numero de prontuário, baseado na regra:
    Prontuario = XX + YYYYY onde = XX é a década do ano atual (24, em 2024)
    seguido da numeração identificadora em ordem
    """

    last_paciente = CadastroPacientes.objects.order_by('-prontuario_numero').first()

    last_prontuario_numero = last_paciente.prontuario_numero

    last_prontuario_numero_identificador = last_prontuario_numero[-5:]

    novo_prontuario_numero_identificador = int(last_prontuario_numero_identificador.lstrip('0')) + 1

    novo_prontuario_numero_identificador_str = str(novo_prontuario_numero_identificador)

    novo_prontuario_numero_identificador_str = '0' * (
                5 - len(novo_prontuario_numero_identificador_str)) + novo_prontuario_numero_identificador_str

    ano_str = str(datetime.now().year)

    prontuario_inicio = ano_str[2:]

    novo_prontuario_numero = prontuario_inicio + novo_prontuario_numero_identificador_str
    if not last_paciente:
        novo_prontuario_numero = prontuario_inicio + '00001'

        return str(novo_prontuario_numero)
    return novo_prontuario_numero


def validate_numbers(value):
    if value and not re.match("^[0-9]+$", str(value)):
        raise ValidationError("Este campo pode conter apenas números")


def validate_letters(value):
    if not value:
        pass

    for char in str(value):
        if not re.match(r"^[A-Za-z\sáéíóúãõâêîôûàèìòùçÁÉÍÓÚÃÕÂÊÎÔÛÀÈÌÒÙÇ]+$", char, re.U):
            raise ValidationError(
                f"O caractere '{char}' não é permitido. Este campo pode conter apenas letras e espaços.")


def validate_date_past(value):
    if value and isinstance(value, date):
        if value > timezone.now().date():
            raise ValidationError("A data não pode estar no futuro!")

    else:
        pass


class CadastroPacientes(models.Model):
    nome = models.CharField(verbose_name='Nome do Paciente', max_length=100,
                            validators=[validate_letters, MinLengthValidator(limit_value=5)])
    prontuario_numero = models.CharField(verbose_name='Nº de Prontuario', max_length=7,
                                         default=create_prontuario_numero,
                                         unique=True, validators=[validate_numbers, MinLengthValidator(limit_value=7)])
    nascimento = models.DateField(verbose_name='Data de Nascimento', help_text='dd/mm/aaaa',
                                  validators=[validate_date_past])
    responsavel_legal = models.CharField(verbose_name='Responsável Legal', max_length=100,
                                         null=True, blank=True, validators=[validate_letters,
                                                                            MinLengthValidator(limit_value=5)])
    cpf_responsavel_legal = models.CharField(verbose_name='CPF do Responsável', max_length=11, blank=True, null=True,
                                             validators=[validate_numbers, MinLengthValidator(limit_value=11)])

    data_inicio = models.DateField(verbose_name='Data de Inicio', help_text='dd/mm/aaaa', default=datetime.now)
    data_final = models.DateField(verbose_name='Data do Desligamento', help_text='dd/mm/aaaa', blank=True, null=True,
                                  validators=[validate_date_past])

    desligado = models.BooleanField(verbose_name='Desligado', help_text='Paciente desligado', default=False)
    cpf_numero = models.CharField(verbose_name='CPF', max_length=11, unique=True,
                                  help_text="CPF de menores consta na Certidão de Nascimento",
                                  validators=[validate_numbers, MinLengthValidator(limit_value=11)])

    MOD_CHOICES = (
        (0, 'Individual'),
        (1, 'Grupo'),
        (2, 'Casal'),
    )
    modalidade_atendimento = models.IntegerField(verbose_name='Modalidade', choices=MOD_CHOICES, default=0)
    grupo = models.ForeignKey(
        'CadastroGrupos',
        related_name='membros',
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    convenio = models.ForeignKey(
        'ConveniosAceitos',
        related_name='pacientes',
        on_delete=models.PROTECT
    )
    carteirinha_convenio = models.CharField(verbose_name='Número do Convênio',
                                            max_length=50, blank=True, null=True,
                                            validators=[validate_numbers, MinLengthValidator(limit_value=7)])
    terapeuta = models.ForeignKey(
        'CadastroProfissionais',
        related_name='pacientes',
        on_delete=models.PROTECT
    )
    endereco_rua = models.CharField(verbose_name='Endereço', max_length=100,
                                    validators=[MinLengthValidator(limit_value=10)])
    endereco_bairro = models.CharField(verbose_name='Bairro', max_length=50,
                                       validators=[MinLengthValidator(limit_value=3)])
    endereco_numero = models.CharField(verbose_name='Número', max_length=7, validators=[validate_numbers])
    endereco_complemento = models.CharField(verbose_name='Complemento', max_length=100,
                                            validators=[MinLengthValidator(limit_value=4)])
    telefone_numero = models.CharField(verbose_name='Telefone', max_length=11,
                                       validators=[validate_numbers, MinLengthValidator(limit_value=11)])
    cidade = models.CharField(verbose_name='Cidade', max_length=100, validators=[validate_letters,
                                                                                 MinLengthValidator(limit_value=3)])
    cep_numero = models.CharField(verbose_name='CEP', max_length=8, validators=[validate_numbers,
                                                                                MinLengthValidator(limit_value=8)])
    email = models.EmailField(verbose_name='E-mail')
    observacoes = models.TextField(verbose_name='Observações', blank=True, null=True)
    objects = models.Manager()

    def __str__(self):
        return f'{self.nome}, prontuário: {self.prontuario_numero}, terapeuta: {self.terapeuta}'

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'
        ordering = ["nome"]
        permissions = [
            ('transfer_pac', 'Transferir Paciente (Terapeutas)'),
            ('deslig_pac', 'Desligar Paciente (Terapeutas)'),
            ('add_pac_group', 'Adicionar Paciente a Grupo (Terapeutas)'),
            ('remove_pac_from_group', 'Remover Paciente de um Grupo (Terapeutas)')
        ]


class ConveniosAceitos(models.Model):
    nome = models.CharField(verbose_name='Convênio', max_length=50, validators=[MinLengthValidator(limit_value=3)])
    cnpj_numero = models.CharField(verbose_name='CNPJ', max_length=14, blank=False, null=True,
                                   validators=[validate_numbers, MinLengthValidator(limit_value=14)])
    endereco_rua = models.CharField(verbose_name='Endereço', max_length=100, blank=False, null=True,
                                    validators=[MinLengthValidator(limit_value=10)])
    endereco_bairro = models.CharField(verbose_name='Bairro', max_length=50, blank=False, null=True,
                                       validators=[MinLengthValidator(limit_value=3)])
    endereco_numero = models.CharField(verbose_name='Número', max_length=7, blank=False, null=True,
                                       validators=[validate_numbers])
    endereco_complemento = models.CharField(verbose_name='Complemento', max_length=100, blank=False, null=True,
                                            validators=[MinLengthValidator(limit_value=4)])
    cidade = models.CharField(verbose_name='Cidade', max_length=20, blank=False, null=True,
                              validators=[validate_letters, MinLengthValidator(limit_value=3)])
    cep_numero = models.CharField(verbose_name='CEP', max_length=8, blank=False, null=True,
                                  validators=[validate_numbers, MinLengthValidator(limit_value=8)])
    responsavel_contato = models.CharField(verbose_name='Nome do Resposável', max_length=50, blank=False, null=True,
                                           validators=[validate_letters, MinLengthValidator(limit_value=3)])
    telefone_numero = models.CharField(verbose_name='Telefone', max_length=11, blank=False, null=True,
                                       validators=[validate_numbers, MinLengthValidator(limit_value=11)])
    email = models.EmailField(verbose_name='E-mail para Contato', blank=False, null=True, )
    observacoes = models.TextField(verbose_name='Observações', blank=True, null=True)
    objects = models.Manager()

    def __str__(self):
        return f'{self.nome}'

    class Meta:
        verbose_name = 'Convênio'
        verbose_name_plural = 'Convênios'
        permissions = [
            ('add_convenio', 'Adicionar Novo Convenio (Administrativos)')
        ]


class CadastroProfissionais(models.Model):
    nome = models.CharField(verbose_name='Nome', max_length=100,
                            unique=True, editable=True, validators=[validate_letters])
    conselho_codigo = models.CharField(verbose_name='CRP', max_length=5, unique=True,
                                       editable=True, validators=[validate_numbers])
    STATUS_POS_CHOICES = (
        (0, 'Nível 1 - Incompleto'),
        (1, 'Nível 1 - Completo'),
        (2, 'Nível 2 - Incompleto'),
        (3, 'Nível 2 - Completo'),
        (4, 'Nível 3 - Incompleto'),
        (5, 'Nível 3 - Completo'),
    )
    pos_grad_status = models.IntegerField(verbose_name='Status Pós', choices=STATUS_POS_CHOICES, default=0)

main/templates/add_pac_grupo.html
{% extends 'middleman1.html' %}
{% load bootstrap5 %}
{% load static%}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>{% block title %} Adicionar Pacientes {% endblock %}</title>
</head>
<body>
<div class="page-container">
    {% block content %}

    {% if sucesso %}
    <p class="alert alert-success">
        Grupo registrado com sucesso! <br>
        <a href="{% url 'main:homepage' %}"> Voltar ao Inicio </a>
    </p>
    {% else %}
    <form method="post">
  {% csrf_token %}
  {{ form }}
  <table>
    <thead>
      <tr>
        <th>Checkbox</th>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      {% for paciente in pacientes %}
        <tr>
          <td><input type="checkbox" name="selected_items" value="{{ paciente.id }}"></td>
          <td>{{ paciente.nome }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <input type="submit" value="Adicionar Pacientes ao Grupo">
</form>
    {% endif %}
    {% endblock %}
</div>
</body>

    <footer class="footer">
        criado por Mário P. Bernardes, 2023
    </footer>
</html>

main/templates/admin_main.html
{% extends 'middleman1.html' %}
{% load bootstrap5 %}
{% load static%}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>{% block title %} Administração {% endblock %}</title>
</head>
<body>
<div class="page-container">

    {% block content %}
        <h1> Bem Vindo {{ request.user.username }} !</h1>

        <a href="{% url 'main:novo' %}"> Cadastrar Paciente </a> <br>
        <a href="{% url 'main:convenio' %}"> Cadastrar Convênio </a> <br>
        <a href="{% url 'main:usuario' %}"> Cadastrar Terapeuta </a> <br>
        <a href="{% url 'main:index-perfil' %}"> Cadastros </a> <br>
        <a href="{% url 'main:gerar-producao' %}"> Relatório de Produção </a> <br>

    {% endblock %}
</div>
</body>

    <footer class="footer">
        criado por Mário P. Bernardes, 2023
    </footer>
</html>

main/templates/error.html
{% extends 'middleman1.html' %}

{% block title %}Ops!{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between align-items-baseline">
        <h1>Opa! Aconteceu um problema!</h1>
    </div>

    <div class="alert-info mb-2">
        Já enviamos o problema para nossa equipe e vamos trabalhar o mais rápido o possível em corrigi-lo.
    </div>
{% endblock %}

main/templates/grupo_detalhes.html
{% extends 'middleman1.html' %}
{% load bootstrap5 %}
{% load static%}
<head>
        <title>{% block title %} Grupo {{ grupo.prontuario_grupo_numero }} {% endblock %}</title>

</head>
<!DOCTYPE html>
<html lang="pt-br">
<body>
<div class="page-container">

{% block content %}
<h1> Grupo: {{ grupo.label }} <br>
     Prontuário nº:  {{ grupo.prontuario_grupo_numero }}
</h1>
    <ul>
            <li>
                Data de Início: {{ grupo.data_inicio}} <br>
                Número de sessões: {{ count }} <br>
                Participantes: {% for participante in participantes %} <br>
                <li>
                Nome: {{ participante.nome }}
                Prontuário Individual: {{ participante.prontuario_numero }}
                Contato: {{ paciente.telefone_numero }} <br>

                <a href="{% url 'main:remove_paciente' prontuario_numero=participante.prontuario_numero prontuario_grupo_numero=grupo.prontuario_grupo_numero%}"> Remover participante </a>

                </li>
                {% empty %}
                <li>No entries found.</li>
                {% endfor %}

            </li>

            <a href="{% url 'main:homepage' %}"> Voltar ao Inicio </a>

    </ul>
{% endblock %}
</div>
</body>

    <footer class="footer">
        criado por Mário P. Bernardes, 2023
    </footer>
</html>

main/templates/index.html
{% extends 'middleman1.html' %}
{% load bootstrap5 %}
{% load static%}

<!DOCTYPE html>
<html lang="pt-br">
<head>
        <title>{% block title %} Indice {% endblock %}</title>

</head>
<body>
<div class="page-container">

{% block content %}
<h1>Bem Vindo {{ request.user.username }} ! </h1>
    {% csrf_token %}

    <ul>
        <h2> Pacientes: </h2>
        {% for paciente in active_pacientes %}
            <li>
                {{ paciente.nome }} - {{ paciente.prontuario_numero }}
                <a href="{% url 'main:add_entrada' prontuario_numero=paciente.prontuario_numero %}"> Registrar Nova Consulta </a> /
                <a href="{% url 'main:prontuario' prontuario_numero=paciente.prontuario_numero %}"> Ver Histórico </a> /
                <a href="{% url 'main:enviar_arquivo_paciente' prontuario_numero=paciente.prontuario_numero %}"> Adicionar Arquivos  </a> /
                <a href="{% url 'main:transferencia' prontuario_numero=paciente.prontuario_numero %}"> Transferir </a> /
                <a href="{% url 'main:desligamento' prontuario_numero=paciente.prontuario_numero %}"> Desligar </a> /
                <a href="{% url 'main:dadospac' prontuario_numero=paciente.prontuario_numero %}"> Detalhes </a>

            </li>
        {% empty %}
            <li>No entries found.</li>
        {% endfor %}

        <h2> Pacientes Desligados: </h2>
        {% for paciente in inactive_pacientes %}
            <li>
                {{ paciente.nome }} - {{ paciente.prontuario_numero }}
                <a href="{% url 'main:prontuario' prontuario_numero=paciente.prontuario_numero %}"> Ver Histórico </a> /
                <a href="{% url 'main:dadospac' prontuario_numero=paciente.prontuario_numero %}"> Detalhes </a>

            </li>
        {% empty %}
            <li>No entries found.</li>
        {% endfor %}
    </ul>
    <ul>
        <h2> Grupos:
</h2>
        <br> <a href="{% url 'main:add-grupo' %}"> Criar Novo Grupo </a>

        {% for grupo in active_grupos %}
            <li>
                {{ grupo.label }} - {{ grupo.prontuario_grupo_numero }}
                {% if grupo.prontuario_grupo_numero %}
                    <a href="{% url 'main:add-entrada-grupo' prontuario_grupo_numero=grupo.prontuario_grupo_numero %}"> Registrar Nova Consulta </a> /
                    <a href="{% url 'main:grupo-prontuario' prontuario_grupo_numero=grupo.prontuario_grupo_numero %}"> Ver Histórico </a> /
                    <a href="{% url 'main:add-pac-grupo' grupo_id=grupo.id %}"> Adicionar Participante </a> /
                    <a href="{% url 'main:transfer-grupo' prontuario_grupo_numero=grupo.prontuario_grupo_numero %}"> Transferir </a> /
                    <a href="{% url 'main:deslig-grupo' prontuario_grupo_numero=grupo.prontuario_grupo_numero %}"> Desligar </a> /
                    <a href="{% url 'main:dados-grupo' prontuario_grupo_numero=grupo.prontuario_grupo_numero %}"> Detalhes </a>
                {% else %}
                <li> Não Encontrado </li>
                {% endif %}
            </li>
        {% empty %}
            <li>No entries found.</li>
        {% endfor %}

         <h2> Grupos Finalizados: </h2>
        {% for grupo in inactive_grupos %}
            <li>
                {{ grupo.label }} - {{ grupo.prontuario_grupo_numero }}
                <a href="{% url 'main:grupo-prontuario' prontuario_grupo_numero=grupo.prontuario_grupo_numero %}"> Ver Histórico </a> /
                <a href="{% url 'main:dados-grupo' prontuario_grupo_numero=grupo.prontuario_grupo_numero %}"> Detalhes </a>

            </li>
        {% empty %}
            <li>No entries found.</li>
        {% endfor %}

    </ul>
{% endblock %}
</div>
</body>

    <footer class="footer">
        criado por Mário P. Bernardes, 2023
    </footer>
</html>

main/templates/list_perfils.html
{% extends 'middleman1.html' %}
{% load bootstrap5 %}
{% load static%}

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} Cadastro Geral {% endblock %}</title>

    </head>
    <body>
        <div class="page-container">

        {% block content %}
        <h1>Bem Vindo {{ request.user.username }} ! </h1>
            {% csrf_token %}
            <ul>
                <h2> Pacientes Ativos: </h2>
                    {% for paciente in lis_pacientes_ativos %}
                        <li>
                        {{ paciente.nome }} - {{ paciente.prontuario_numero }}
                        <a href="{% url 'main:enviar_arquivo_paciente' prontuario_numero=paciente.prontuario_numero %}"> Adicionar Arquivo </a> /
                        <a href="{% url 'main:dadospac' prontuario_numero=paciente.prontuario_numero %}"> Ver Detalhes </a> <br>

                        </li>
                    {% empty %}
                        <li>No entries found.</li>
                    {% endfor %}

                <h2> Pacientes Inativos: </h2>
                    {% for paciente in lis_pacientes_inativos %}
                        <li>
                        {{ paciente.nome }} - {{ paciente.prontuario_numero }}
                        <a href="{% url 'main:religamento' prontuario_numero=paciente.prontuario_numero %}"> Reativar </a> <br>
                        </li>
                    {% empty %}
                        <li>No entries found.</li>
                    {% endfor %}
                <h2> Terapeutas: </h2>
                    {% for terapeuta in list_terapeutas %}
                        <li> {{ terapeuta.nome }} - {{ terapeuta.conselho_codigo }} - <a href="{% url 'main:perfil' terapeuta_codigo=terapeuta.conselho_codigo %}"> Detalhes </a> /
                        <a href="{% url 'main:cadastrar_formacao' terapeuta_codigo=terapeuta.conselho_codigo %}"> Adicionar Formação </a> /
                        <a href="{% url 'main:enviar_arquivo_terapeuta' terapeuta_codigo=terapeuta.conselho_codigo %}"> Adicionar Arquivo </a> <br>

                        </li>
                    {% empty %}
                        <li>No entries found.</li>
                    {% endfor %}
            </ul>
        {% endblock %}

        </div>
    </body>

    <footer class="footer">
        criado por Mário P. Bernardes, 2023
    </footer>
</html>

main/templates/user_perfil.html
{% extends 'middleman1.html' %}
{% load bootstrap5 %}
{% load static%}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>{% block title %} Informações Pessoais de {{ terapeuta.nome}} {% endblock %}</title>
</head>
<body>
<div class="page-container">

{% block content %}
<h1>Informações Pessoais de {{ terapeuta.nome }}:</h1>

    <h3> Pessoal : </h3>

        <li>Data de Nascimento: {{ terapeuta.nascimento_data }}  </li>
        <li>CPF: {{ terapeuta.cpf_numero | format_cpf }} , RG: {{terapeuta.rg_numero}} {{terapeuta.rg_emissor}} </li>
        <li>Email: {{ terapeuta.email }} </li>
        <li>Telefone: {{ terapeuta.telefone_numero | format_phone_number }} </li>
        <li>Endereço: Rua: {{ terapeuta.endereco_rua }}, {{ terapeuta.endereco_numero }} <br>
            {{terapeuta.endereco_complemento}} , {{ terapeuta.endereco_bairro }}, {{ terapeuta.cidade }},
        <br> CEP: {{ terapeuta.cep_numero }} </li>
        <br>
        <h4> Profissional: </h4>
        <li>CRP: {{ terapeuta.conselho_codigo }} </li>
        <li>Status Pós: {{ terapeuta.get_pos_grad_status_display }} </li>
    <br>
    <h6> Formação: </h6>
        {% for curso in historico %}
            <li>
                {{ curso.curso }} - {{ curso.instituicao }} - {{ curso.ano_conclusao }} <br>
                <a href="{% url 'main:view_certificado' curso_id=curso.id %}"> Ver Certificado </a>
            </li>
        {% empty %}
            <li> Sem arquivos para exibir.</li>
        {% endfor %}
    <h5> Arquivos: </h5>
        {% for media in pdf_media %}
            PDF:
            <li>
                {{ media.description }} - <a href="{% url 'main:terapeuta/pdf' media_id=media.id %}"> Visualizar </a>
            </li>
        {% empty %}
            <li> Sem arquivos para exibir.</li>
        {% endfor %}
        <br>
            Imagens: <br>
            {% for media in image_media %}
                <li>
                    {{ media.description }} - <a href="{% url 'main:terapeuta/image' media_id=media.id %}"> Visualizar </a>
                </li>
            {% empty %}
                <li> Sem arquivos para exibir.</li>
            {% endfor %}
{% endblock %}
</div>
</body>

    <footer class="footer">
        criado por Mário P. Bernardes, 2023
    </footer>
</html>